Fix <rdar://23248290> Name lookup: "Cannot convert type 'Int' to expected argument type 'Int'" while trying to initialize ivar of generic type in class scope
Type resolution wasn't looking through property initializer decl contexts
to find out whether an unbound generic type reference was referring to the
enclosing type.  Previously we'd reject this with:

error: cannot convert value of type 'Int' to specified type 'Int'
  private var data: Int = Matrix4.size()
                          ~~~~~~~~^~~~~~

which was super confusing.  The problem was that we weren't resolving
Matrix4 to Matrix4<T>.