Fix rdar://23013334 DI QoI: Diagnostic claims that property is being used when it actually isn't
Partial applications of a root self value are an escape point, not a load.  This
improves the diagnostic in this case from:

t.swift:18:24: error: variable 'self.B' used before being initialized
    self.A.withCString {  cString -> () in
                       ^

to:

t.swift:18:24: error: variable 'self.B' captured by a closure before being initialized
    self.A.withCString {  cString -> () in
                       ^